"""followers

Revision ID: 50114dfea8a4
Revises: 38390d97b069
Create Date: 2019-04-13 13:45:38.299132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50114dfea8a4'
down_revision = '38390d97b069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
